# application.yml - 通用配置
server:
  port: 8080
spring:
  profiles:
    active: prod
  application:
    name: nav-server
  error:
    whitelabel:
      enabled: false
      include-message: never
      include-binding-errors: never
  data:
    redis:
      port: 6379
      host: 38.47.121.89
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: INFO
    com.dawn.nav.authentication: INFO
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    login.jwt: INFO  # 确保这是一个有效的包名或记录器名称