# application.yml - 通用配置
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://dogyun-jp.lolis.moe:3306/gonav?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod
  application:
    name: nav-server
#  error:
#    whitelabel:
#      enabled: false
#      include-message: never
#      include-binding-errors: never
  data:
    redis:
      port: 6379
      host: dogyun-jp.lolis.moe
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: DEBUG
    com.dawn.gonav.authentication: DEBUG